name: "Publish all libs, Arrow-stack and Docs"

on:
  push:
    branches:
      - windows_build
    paths:
      - 'arrow-libs/**'
      - '.github/**'

env:
  BASEDIR: ${{github.workspace}}/arrow-libs
  JAVA_OPTS: -Xms512m -Xmx1024m
  SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
  SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:

  publish_windows:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore Gradle cache
        id: cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: "Set env"
        run: ${GITHUB_WORKSPACE}/.github/scripts/set-env.sh
        shell: bash

      - name: "Show env"
        run: ${GITHUB_WORKSPACE}/.github/scripts/show-env.sh
        shell: bash
